name: Solar System Workflow
run-name: Solar System - ${{ github.ref_name }} - ${{ github.run_number }} - ${{ github.actor }}
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}



jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [24, 22, 20]
            os: [ubuntu-latest, windows-latest, macos-latest]
            exclude:
              - node-version: 20
                os: [macos-latest, windows-latest]
              - node-version: 22
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        # runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix['node-version'] }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v6
          with:
            name: Mocha-Test-Result-${{ matrix.os }}-Node-${{ matrix['node-version'] }}
            path: test-results.xml

    Code-Coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        needs: unit-testing
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v6
          with:
            node-version: 24
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm run coverage
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v6
          with:
            name: Code-Coverage-Report
            path: coverage
            retention-days: 5
            